#!/bin/bash

# Copyright 2015, 2016, EMC, Inc.

# debian packages expected...
# apt-get install git pbuilder dh-make ubuntu-dev-tools devscripts
# apt-get install nodejs nodejs-legacy npm

set -e
set -x

# $1 should be a file which contains the release version.
# For example:  PKG_VERSION=1.2.3-rc-abc...
if [ -f "$1" ];then
    source $1
fi

rm -rf packagebuild
git clone . packagebuild
pushd packagebuild
cp ../package.json .

rm -rf node_modules
npm install --production --cache=`pwd`
git log -n 1 --pretty=format:%h.%ai.%s > commitstring.txt

export DEBEMAIL="hwimo robots <hwimo@hwimo.lab.emc.com>"
export DEBFULLNAME="The HWIMO Robots"

if [ ! -z "$PKG_VERSION" ];then
    if [[ $PKG_VERSION =~ ^[0-9.]+$ ]];then
        dch -r ""
    else
        COMMIT_STR=`git log -n 1 --oneline`
        dch -v $PKG_VERSION -u low $COMMIT_STR -b -m
    fi
fi

debuild --no-lintian --no-tgz-check -us -uc
popd
