#!/bin/bash

# Copyright 2015, EMC, Inc.

set -e
set -x

rm -rf node_modules
npm install

# Checks the code against the jshint options
./node_modules/.bin/jshint -c .jshintrc --reporter=checkstyle lib index.js > checkstyle-result.xml || true
./node_modules/.bin/jshint -c .jshintrc lib index.js || true


# Runs the mocha tests and reports the code coerage.
./node_modules/.bin/istanbul cover -x "**/spec/**" ./node_modules/.bin/_mocha -- $(find spec -name '*-spec.js') -R xunit-file --require spec/helper.js 
./node_modules/.bin/istanbul report cobertura

